name: vaidhya_front_end
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+3 # Format is version_name+version_code

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  flutter_riverpod: ^2.6.1
  flutter_launcher_icons: ^0.14.4
  razorpay_flutter: ^1.4.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  image_picker: ^1.1.2
  google_maps_flutter: ^2.5.0

  flutter_google_places:
    ^0.3.0
    # Updated from 12.0.0
    # Updated from 4.0.0
  intl: ^0.20.2
  table_calendar: ^3.2.0
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  url_launcher: ^6.3.1

dependency_overrides:
  google_api_headers: ^4.2.0
  # Add these overrides to force latest versions
  geolocator_android: ^4.6.1
  geocoding_android: ^3.3.1
  google_maps_flutter_android: ^2.14.7
  image_picker_android: ^0.8.12+13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.png"
  adaptive_icon_background: "#FFFFFF" # Optional: for Android adaptive icons
  adaptive_icon_foreground: "assets/images/applogo.png"
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
